services:
  - type: web
    name: unbiased-ai-platform
    runtime: python
    runtimeVersion: 3.12.9
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    buildCommand: pip install -r requirements.txt
